# Generated by Django 5.1.5 on 2025-02-01 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=512, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='trips',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='city',
        ),
        migrations.AddField(
            model_name='trip',
            name='attractions',
            field=models.ManyToManyField(related_name='trips', to='trips.attraction'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='type',
            field=models.IntegerField(choices=[(0, 'SIGHTSEEING'), (1, 'RECREATION'), (2, 'AMUSEMENT')]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='attraction',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='trips.city'),
        ),
        migrations.AddField(
            model_name='trip',
            name='cities',
            field=models.ManyToManyField(related_name='trips', to='trips.city'),
        ),
    ]
