# Generated by Django 5.1.5 on 2025-02-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_city_remove_attraction_trips_remove_trip_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attraction',
            name='type',
        ),
        migrations.AddField(
            model_name='attraction',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
