# Generated by Django 5.1.5 on 2025-02-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_remove_attraction_type_attraction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='city',
            field=models.CharField(blank=True, default='unknown', max_length=512, null=True),
        ),
    ]
